### ISSUE TITLE
Clicks originating within a link are not handled

### ISSUE THREAD

**Issue by willcosgrove** [phlex-ruby/phlex.js#1]
If you have this structure:

```html
<a data-action="morph" data-target="parent" data-fragment="parent">
  <img src="nyancat.gif" />
</a>
```

And you click on the image, the `event.target` will not be an `HTMLAnchorElement` and so the click handling is lost.

**Comment by joeldrapper** [comment]
Did you implement a fix for this in your demo app already @willcosgrove?

**Comment by willcosgrove** [comment]
Yes I did, I can open a PR with it later this evening
